export enum ClassErrorCode {
  CLASS_NOT_FOUND = "CLASS_NOT_FOUND",
  CLASS_CODE_ALREADY_EXISTS = "CLASS_CODE_ALREADY_EXISTS",
  CLASS_SUBJECT_ALREADY_EXISTS = "CLASS_SUBJECT_ALREADY_EXISTS",
  INACTIVE_CLASS = "INACTIVE_CLASS",
  INACTIVE_SUBJECT = "INACTIVE_SUBJECT",
  INACTIVE_TEACHER = "INACTIVE_TEACHER",
}
