export enum AdminErrorCode {
  PARENT_NOT_FOUND = "PARENT_NOT_FOUND",
  INVALID_PARENT_STATUS_TRANSITION = "INVALID_PARENT_STATUS_TRANSITION",
  TEACHER_NOT_FOUND = "TEACHER_NOT_FOUND",
  INVALID_TEACHER_STATUS_TRANSITION = "INVALID_TEACHER_STATUS_TRANSITION",
  TEACHER_INVITATION_NOT_ALLOWED = "TEACHER_INVITATION_NOT_ALLOWED",
}
