export enum AdminErrorCode {
  TEACHER_NOT_FOUND = "TEACHER_NOT_FOUND",
  INVALID_TEACHER_STATUS_TRANSITION = "INVALID_TEACHER_STATUS_TRANSITION",
  TEACHER_INVITATION_NOT_ALLOWED = "TEACHER_INVITATION_NOT_ALLOWED",
}
